config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "users#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  scope "/" do
    resources :users, only: [:index, :show] do
      resources :posts, only:[:index, :show, :new, :create] do
        resources :comments, only:[:new, :create]
        resources :likes, only:[:new, :create]
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_user_posts_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.update_posts_counter
  end

  def update_likes_counter
    update_column(:likes_counter, likes.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    Post.where(author_id: id).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :allowed_parameters, if: :devise_controller?

  def allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :attr_user_post

  def new
    @comment = Comment.new(user: current_user, post: @post)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post_id = params[:post_id] # Or use a similar approach to get the post

    if @comment.save
      flash[:success] = 'Comment added successfully'
      redirect_to user_post_path(current_user, @comment.post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def attr_user_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :attr_user_post

  def new
    @like = Like.new(user: current_user, post: @post)
  end

  def create
    @current_user = current_user
    @like = Like.new(user: @current_user, post: @post)

    if @like.save!
      flash[:success] = ' Liked '
      redirect_to user_post_path(@user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def attr_user_post
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @current_user = current_user
    @posts = Post.where(author_id: @user.id)
  end

  def show
    @post = Post.find(params[:id])
    @current_user = current_user
    @author = User.find(@post.author_id)
    @comments = @post.comments
    @comment = Comment.new(user: @current_user, post: @post)
  end

  def new
    if user_signed_in?
      @user = current_user
      @post = @user.posts.new
      respond_to do |format|
        format.html { render :new, locals: { post: @post } }
      end
      puts 'created'
    else
      redirect_to new_user_session_path, alert: 'Please log In'
    end
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    @post.author_id = @user.id
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = ' Post created '
          redirect_to user_post_path(@user, @post)
        else
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_new.html.erb
<%= form_with model: @comment, url: user_post_comments_path(@current_user.id, @post.id), method: :post, class: 'border-4 border-pink-900', local: true do |f| %>
  <div>
    <%= f.label :text, class: 'font-bold' %><br>
    <%= f.text_area :text, class: 'rounded border-2 border-gray-300' %>
  </div>
  <div>
    <%= f.submit 'Comment', class: 'bg-pink-900 text-white border-4 border-pink-900 text-white cursor-pointer py-2 px-4' %>
  </div>
<% end %>
<%= render partial: "partials/errors", locals: { errors: @comment.errors } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <div class="container mx-auto py-4">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_comments_list.html.erb
<div class='post_comments'>
  <% if comments.empty? || comments.nil? %>
    <span class='comment_item'><%= "No comment" %></span>
  <% else %>
    <ul class='comment_list'>
      <% comments.each_with_index do |comment, index| %>
        <li class='comment_item'><%= comment.user.name %>: <%= comment.text %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/partials/_comments_lists.html.erb
<div class='post_comments'>
  <% if comments.empty? || comments.nil? %>
    <span class='comment_item'><%= "No comment" %></span>
  <% else %>
    <ul class='comment_list'>
      <% comments.each_with_index do |comment, index| %>
        <li class='comment_item'><%= comment.user.name %>: <%= comment.text %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/partials/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.count, "error") %> Errors occured:</h2>

    <ul>
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_post_item.html.erb
<div class=''>
<h4 class='text-xl bp-3 text-pink-900'>
<%= link_to user_post_path(post.author, post) do %>
  <div class='py-2 text-pink-900'>
    <span class='text-pink-900'>Post <%=index + 1%> - </span>
    <%= post.title %>
  </div>
<% end %>
</h4>
  <div class=''>
    <div class=''>
      <%=post.text%>
    </div>
    <div class='text-sm text-pink-600'>
      <span>Comment: <%=post.comments_counter%>, </span>
      <span>Like: <%=post.likes_counter%> </span>
    </div>
  </div>
</div>

app/views/partials/_user_profile.html.erb
<a href="/users/<%= user.id %>">
  <div class='mb-4 flex gap-2 items-center border-2 border-pink-900 rounded-2xl overflow-hidden shadow'>
    <div class='m-3.5'>
    <% if user.photo_url.nil? %>
    <%= image_tag "https://cdn2.iconfinder.com/data/icons/instagram-outline/19/11-512.png", alt: "profil image", width: "100px", height: "100px", class: "user_avatar" %>
  <% else%>
    <%= image_tag user.photo_url, alt: "profil image", width: "100px", height: "100px", class: "user_avatar" %>
  <% end %>
    </div>
    <div class='relative w-full'>
      <p class='text-3xl text-pink-900 font-bold'>
          <%= user.name %>
      </p>
      <span class='text-sm text-pink-500 absolute bottom-0 right-4'>
        Number of posts: <%= user.posts_counter%>
      </span>
    </div>
  </div>
</a>

app/views/posts/comment_form.html.erb
# app/views/comments/new.html.erb
<%= form_with model: Comment.new, url: comments_path, local: true do |form| %>
  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit 'Create Comment' %>
<% end %>

app/views/posts/index.html.erb
<div class='user_profile'>
  <%= render partial: "partials/user_profile", locals: { user: @user } %>
  <div class='user_posts'>
    <div class="add_post_btn">
      <%= link_to 'Add Post', new_user_post_path(@current_user.id) %>
    </div>
    <%if @posts.present?%>
    <ul id='users_list'>
      <% @posts.each_with_index do |post, index| %>
        <li class="all_user_post">
          <%= render partial: "partials/post_item", locals: { post: post, index:index } %>
          <% comments=post.five_recent_comments %>
          <%= render partial: "partials/comments_list", locals: { comments: comments} %>
        </li>
      <% end %>
    </ul>
  <%else%>
    <%='No post'%>
  <%end%>
  </div>
  <div>
    <button class='bg-pink-900 text-white py-2 px-6 rounded m-1.5'>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new_post_container border-2 border-pink-900 rounded-2xl">
  <h1 class="m-4 font-bold text-pink-900">New post</h1>
  <%= form_with model: @post, url: user_posts_path(@user), method: :post, local: true do |f| %>
    <div class="m-4 font-bold text-pink-600">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="m-4 font-bold text-pink-600">
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </div>
    <div class="m-4 font-bold text-white w-14 h-10 border-4 bg-pink-900 border-pink-900">
      <%= f.submit 'Post' %>
    </div>
  <% end %>
  <%= render partial: "partials/errors", locals: { errors: @post.errors } %>
</div>

app/views/posts/post_form.html.erb
<%= form_with model: Post.new, url: posts_path, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class="user-list">
  <div class="flex justify-between">
    <h3 class="text-2xl"><%= "Post ##{@post.id} by #{@author.name}" %></h3>
    <p class="text-sm text-gray-500">Comments: <%= @post.comments.count %>, Like: <%= @post.likes.count %></p>
  </div>
  <div class="py-4">
  <h3 class="text-3xl"><%= @post.title %></h3>
  <p><%= @post.text %></p>
  </div>
  <div class="">
    <%=button_to 'Like', user_post_likes_path(@current_user.id, @post), method: :post ,  class:' px-4 bg-pink-900 text-white border-4 border-pink-900 text-white'%>
  </div>
  <div class="mt-4">
    <%= render 'comments/new' %>
  </div>
  <ul>
    <% @post.comments.includes([:user]) do |comment| %>
    <li><%= "#{comment.user.name}: #{comment.text}" %></li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<ul id='users_list'>
    <% @users.each do |user| %>
    <li>
         <%= render partial: "partials/user_profile", locals: { user: user } %>
    </li>
    <% end %>
</ul>

app/views/users/show.html.erb
<div class=''>
    <%= render partial: 'partials/user_profile', locals: { user: @user } %>
    <div class='mb-4'>
        <h3 class='text-xl bp-3 text-pink-700 font-bold'>Bio <h3>
        <div class='text-pink-400 border-b-2 border-pink-200 pb-3'>
            <%=@user.bio%>
        </div>
        <div class="add_post_btn m-4">
            <%= link_to 'Add Post', new_user_post_path(@current_user), class: 'bg-pink-800 text-white py-2 px-6 rounded' %>
        </div>
    </div>
    <div class='mb-4'>
        <h3 class='text-xl bp-4 text-pink-700'>Posts<h3>
        <ul class='flex flex-col gap-2'>
            <% @user.three_most_recent_posts.each_with_index do |post, index| %>
                <li>
                    <%= render partial: 'partials/post_item', locals: { post: post, index:index } %>
                </li>
            <% end %>
        </ul>
    </div>
    <div>
        <%= link_to 'See all posts', user_posts_path(@user.id), method: :get, class: 'bg-pink-800 text-white py-2 px-6 rounded'%>
    </div>
</div>